# Task Manager Application Deployment and Service

# Deployment - Manages the Task Manager application Pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-deployment
  namespace: student-02210198   # ✅ fixed namespace
  labels:
    app: taskmanager
    component: frontend
    version: v1
    student: "02210198"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
        version: v1
    spec:
      containers:
      - name: taskmanager
        image: teknathdev/task-manager:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DATABASE_URL
          value: "postgresql://myuser:uWhSZwv54wXv1T7F@10.104.0.6:5432/02210198"
        - name: SECRET_KEY
          value: "kubernetes-secret-key-02210198"
        - name: FLASK_ENV
          value: "production"
